defaultLocation: "48.8584, 2.2945"

googleApiKey: "api-key-from-google" # for geocoding

libraries:
    digitalGlobe:
        connectId: "connect-id-from-digital-globe"
        label: "DG"
        password: "digital-globe-password"
        sensors: []
        queryUrl: "http://evwhs.digitalglobe.com/catalogservice/wfsaccess"
        username: "digital-globe-username"
        viewUrl: "http://evwhs.digitalglobe.com/mapservice/wmsaccess"
    omar:
        label: "OMAR"
        sensors:
            - description: "Commercial: Multispectral"
              name: "msi"
            - description: "Commercial: Panchromatic"
              name: "vis"
        queryUrl: "http://omar.ossim.org/omar/wfs"
        viewUrl: "http://omar.ossim.org/omar/ogc/wms"
    planetLabs:
        apiKey: "api-key-from-planet-labs"
        label: "PLANET"
        password: "planet-labs-password"
        queryUrl: "https://api.planet.com"
        sensors: []
        username: "planet-labs-username"
        viewUrls:
            - "https://tiles0.planet.com/v0/scenes/ortho"
            - "https://tiles1.planet.com/v0/scenes/ortho"
            - "https://tiles2.planet.com/v0/scenes/ortho"
            - "https://tiles3.planet.com/v0/scenes/ortho"

networkSpecific:
    layers:
        enabled: true

securityClassification: "UNCLASSIFIED"

tempFileDir: new File(${System.getProperty("java.io.tmpdir")})
