defaultLocation: "48.8584, 2.2945"

googleApiKey: "api-key-from-google" # for geocoding

libraries:
    digitalGlobe:
        connectId: "connect-id-from-digital-globe"
        label: "DG"
        layerType: "wms"
        name: "digitalGlobe"
        password: "digital-globe-password"
        sensors: []
        queryUrl: "http://evwhs.digitalglobe.com/catalogservice/wfsaccess"
        username: "digital-globe-username"
        viewUrl: "http://evwhs.digitalglobe.com/mapservice/wmsaccess"
    landsat:
        apiKey: "api-key-from-landsat"
        label: "LANDSAT"
        layerType: "xyz"
        name: "landsat"
        password: "landsat-password"
        queryUrl: "https://api.planet.com"
        sensors: []
        username: "landsat-username"
        viewUrls:
            - "https://tiles0.planet.com/v0/scenes/landsat"
            - "https://tiles1.planet.com/v0/scenes/landsat"
            - "https://tiles2.planet.com/v0/scenes/landsat"
            - "https://tiles3.planet.com/v0/scenes/landsat"
    o2:
        label: "O2"
        layerType: "wms"
        name: "o2"
        sensors:
            - description: "Commercial: Multispectral"
              name: "msi"
            - description: "Commercial: Panchromatic"
              name: "vis"
        queryUrl: "http://o2.ossim.org/o2/wfs/getFeature"
        viewUrl: "http://o2.ossim.org/o2/wms/getMap"
    omar:
        label: "OMAR"
        layerType: "wms"
        name: "omar"
        sensors:
            - description: "Commercial: Multispectral"
              name: "msi"
            - description: "Commercial: Panchromatic"
              name: "vis"
        queryUrl: "http://omar.ossim.org/omar/wfs"
        viewUrl: "http://omar.ossim.org/omar/ogc/wms"
    planetLabs:
        apiKey: "api-key-from-planet-labs"
        label: "PLANET"
        layerType: "xyz"
        name: "planetLabs"
        password: "planet-labs-password"
        queryUrl: "https://api.planet.com"
        sensors: []
        username: "planet-labs-username"
        viewUrls:
            - "https://tiles0.planet.com/v0/scenes/ortho"
            - "https://tiles1.planet.com/v0/scenes/ortho"
            - "https://tiles2.planet.com/v0/scenes/ortho"
            - "https://tiles3.planet.com/v0/scenes/ortho"
    rapidEye:
        apiKey: "api-key-from-rapid-eye"
        label: "RAPIDi"
        layerType: "xyz"
        name: "rapidEye"
        password: "rapid-eye-password"
        queryUrl: "https://api.planet.com"
        sensors: []
        username: "rapid-eye-username"
        viewUrls:
            - "https://tiles0.planet.com/v0/scenes/rapideye"
            - "https://tiles1.planet.com/v0/scenes/rapideye"
            - "https://tiles2.planet.com/v0/scenes/rapideye"
            - "https://tiles3.planet.com/v0/scenes/rapideye"

networkSpecific:
    layers:
        enabled: true

securityClassification: "UNCLASSIFIED"

tempFileDir: new File(${System.getProperty("java.io.tmpdir")})
