== Search


The following section describes all the functionality that is available as it relates to the search dialog.


=== Location
This will be the center point around which the search is conducted. TLV will bring its _A_ game and attempt to automatically detect which coordinate format you enter. (DD, DMS & MGRS)

=== Start Date
The start date of the search. The default is 30 days prior to today.

=== End Date
The end date of the search. The default is now.

=== Sensor
Discriminate results to specific sensor types.

=== Tailored GEOINT
Similar to sensors but these are images that have been processed and/or combined. For example, a panchromatic image and multi-spectral image may have been combined to produce a Tailored GEOINT product called PSM.

=== Min. Niirs
The minimum NIIRS (National Imagery Interpretability Rating Scale) in which you are interested. The default is 0.

=== Max. Cloud Cover (%)
The maximum amount of cloud cover you want in any of the images that are returned. The default is 100.

=== Max. Results
The total amount of images you are willing to look through. The default is 10.

NOTE: The ability to examine large amounts of imagery relies heavily on available browser/computer resources.

=== Library
You can select one or more libraries from which to search for imagery. Each selected library will be searched one at a time and the results will be aggregated and sorted before being returned to the browser. The default is the first library.

=== Bookmark It!
Get a URL that captures ALL of the current search parameters. You can use that URL and keep certain parameters fixed and bookmark it so that those parameters are automatically set when you bring up a new session of TLV. For example, let's say you HATE clouds with a passion. You might want to bookmark a URL that has `maxCloudCover=0` parameter. Or perhaps you are only ever interested in panchromatic imagery, you could use `sensor=VIS`.
